# Generated by Django 4.2 on 2023-04-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_facebookurl_profile_githuburl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='InstagramUrl',
            new_name='LinkeInUrl',
        ),
    ]
