# Generated by Django 4.2 on 2023-04-25 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_profile_company_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('compnay_logo', models.ImageField(upload_to='Companies/')),
                ('company_size', models.CharField(max_length=255)),
                ('company_field', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_founded', models.DateField(blank=True, null=True)),
                ('company_revenue', models.CharField(blank=True, max_length=255, null=True)),
                ('company_ceo', models.CharField(blank=True, max_length=255, null=True)),
                ('company_phone_number', models.CharField(max_length=20)),
                ('company_website_url', models.URLField(blank=True, null=True)),
                ('company_twitter_url', models.URLField(blank=True, null=True)),
                ('company_linkedin_url', models.URLField(blank=True, null=True)),
                ('company_facebook_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_field',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_website_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_com',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_company',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ManyToManyField(related_name='services', to='accounts.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_name', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
