# Generated by Django 4.2 on 2023-04-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_company_remove_profile_company_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True, 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelTable(
            name='company',
            table='',
        ),
    ]
