# Generated by Django 4.2 on 2023-04-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_category_options_alter_job_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
