# Generated by Django 4.2 on 2023-04-10 20:16

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='photo',
            field=models.ImageField(upload_to=job.models.upload_pics),
        ),
    ]
