# Generated by Django 4.2 on 2023-04-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_slug_alter_job_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('cv_file', models.FileField(upload_to='apply/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'apply',
                'verbose_name_plural': 'applies',
            },
        ),
    ]
