# Generated by Django 4.2 on 2023-04-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_job_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'get_latest_by': '-published_at', 'ordering': ['-published_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
