# Generated by Django 4.2 on 2023-04-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_company_options_alter_company_table'),
        ('job', '0013_alter_job_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companyName', to='accounts.company'),
            preserve_default=False,
        ),
    ]
